repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-added-large-files # Require LFS for files over 500kB
    - id: check-ast
    - id: check-executables-have-shebangs # Make sure scripts have ok #! lines
    - id: check-merge-conflict # Make sure merge conflicts are fixed
    - id: check-symlinks # Make sure symlinks have valid targets
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
    - id: mixed-line-ending  # Makes sure line-endings are unix style
    - id: trailing-whitespace # Trims trailing whitespace
    - id: check-docstring-first # Verifies that docstrings are placed before code
    - id: debug-statements # Check for debugger imports and py37+ breakpoint() calls in python source.

# Linter for markdown
#- repo: https://github.com/igorshubovych/markdownlint-cli
#  rev: v0.44.0
#  hooks:
#    - id: markdownlint-fix

- repo: meta
  hooks:
#  - id: check-hooks-apply # Ensures that the configured hooks apply to at least one file in the repository
  - id: check-useless-excludes # Ensures that exclude directives apply to any file in the repository.

# Automatic code formatting
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    args: [--line-length=120]

# Sort includes
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
   - id: isort
     name: isort (python)
     args: [--profile=black, --line-length=120]

 # Strict linter
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    args: [--max-line-length=120]
