repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
    -   id: black
        language_version: python3.12
        args: [--target-version=py312, --target-version=py311, --preview, --line-length=120]
