[tool.poetry]
name = "sonic-netbox-zabbix"
version = "0.1.0"
description = "Sync Netbox devices and virtual-machines to Zabbix hosts"
authors = ["Eric Eisenhart <eric.eisenhart@sonic.com>"]
license = "GNU Affero General Public License v3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ConfigArgParse = "^1.7"
pyzabbix = "^1.3.1"
pynetbox = "^7.3.3"
hvac = {version = "^2.2.0", optional = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
